import rtconfig
from building import *

cwd = GetCurrentDir()

# QActive Demo source files
src = Split("""
main.c
""")

# Include paths
path = [cwd]

# Define the QActive demo group
group = DefineGroup('qactive_demo_isr', src,
                   depend = ['PKG_USING_QPC', 'QPC_USING_QACTIVE_DEMO_ISR', 'RT_USING_FINSH'],
                   CPPPATH = path)

Return('group')
